version: "3.7"

networks:
  internal:
    external: false

volumes:
  db:

services:
  backend:
    container_name: vapor-backend
    restart: unless-stopped
    build:
      context: ./
      target: "develop-stage"
    privileged: true
    restart: always
    volumes:
      - "./:/app"
    ports:
      - "8081:8081"
    networks:
      - internal
